stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project Alpha.xcodeproj -scheme Alpha | xcpretty
    - xcodebuild test -project Alpha.xcodeproj -scheme Alpha -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.1' | xcpretty -s
  tags:
    - iOS
